### ISSUE TITLE
The link to "what events are happening" doesn't link to anything.

### ISSUE THREAD

**Issue by DaveParr** [satRdays/satRdays#12]
The link button is labelled 'satrday' and just opens a link back to the main page. Is there an existing calendar somewhere? 

Happy to have a crack at a pr is there's an existing calendar process held somewhere?

**Comment by stephlocke** [comment]
If you're up for some work to get Cardiff added, could you:

- [ ] In `data/carousel` rename capetown.yaml to cardiff.yaml and change the details
- [ ] Add a page in `content` with a table of events (past n upcoming)
- [ ] Change the [config](https://github.com/satRdays/satRdays/blob/d2f8512ea0df2f48bcd21a38d6722213156fcf6f/config.toml#L101) to point to the page with upcoming events listed

**Comment by DaveParr** [comment]
Have PR up for 1 and 2
#14 
#16 

Also spotted some small typos in FAQ
#15 

I have had a pass at 3, but wanted to check I'd interpreted correctly before PR. [A version of the config.toml](https://github.com/DaveRGP/satRdays/blob/eventsContentPage/config.toml) with the change to `link_url` line 101 is on the eventsContentPageBranch. Was the what you meant?
