### ISSUE TITLE
Sponsors

### ISSUE THREAD

**Issue by csgillespie** [satRdays/satRdays#13]
The current list of sponsors is listed at the bottom of the meet-up, http://capetown2018.satrdays.org/

The result is that sponsors get very few views. For large companies, this is probably not a big deal. But for smaller companies - say based in the North East of England ;) - it will make them much more reticient in sponsoring events not in their home region. 

A simple solution is to move the sponsor list up the page. The icons could be shrunk so as not to annoy viewers.

**Comment by stephlocke** [comment]
Organisers will have control over the location of elements of their event pages. For the root satRdays site, perhaps as well as a global sponsors section we should have a past local sponsors section and include logos and sites for everyone who has /is sponsoring a satrdays for extra exposure?

**Comment by csgillespie** [comment]
> Organisers will have control over the location of elements of their event pages.

True, but no-one would change the order.

> For the root satRdays site,...  include logos and sites for everyone

Yep good idea. Also, the twitter account could thank a different local sponsor each week. Just set off as a cron-type job.
